### ISSUE TITLE
SonarCloud telepítése

### ISSUE THREAD

**Issue by kovbe11** [BME-MIT-IET/iet-hf2021-snek#1]
Statikus analízishez SonarCloudot szeretnénk használni.

**Comment by darkpanther99** [comment]
Kis tanári segítséggel, de működik a SonarCloud. Talált is egy rakás code smellt, bugot, amiken dolgozhatunk. https://sonarcloud.io/dashboard?id=BME-MIT-IET_iet-hf2021-snek

**Comment by darkpanther99** [comment]
Szerintem ezt az issuet zárjuk, és nyissunk majd egy újat, ahol a SonarCloud által mutatott hibák javításait beszéljük meg.
