### ISSUE TITLE
CI beüzemelése

### ISSUE THREAD

**Issue by kovbe11** [BME-MIT-IET/iet-hf2021-snek#2]
El kell dönteni, hogy a Github Actionst használjuk, vagy az eredeti repoban lévő Travist.

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/3
Várom a Reviewt.

**Comment by kovbe11** [comment]
Zárom az issuet, mivel megfelelően működik a github actions.
