### ISSUE TITLE
Unit tesztek készítése és kódlefedettség mérése

### ISSUE THREAD

**Issue by darkpanther99** [BME-MIT-IET/iet-hf2021-snek#4]
Pythonos unittest package segítségével vannak már írva tesztek a repoban. Ezekhez kéne kitalálni újakat, amiket le tudunuk futtatni. Emellett kéne mérni a kódlefedettséget, amihez ezt: https://about.codecov.io/ vagy ezt: https://coveralls.io/ használhatnánk. Össze kéne kapcsolni a Github Actions CI rendszerrel, és akkor minden pushra a tesztfutások mellett lefutna a kódlefedettség mérés is.

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/10
Kódlefedettség mérést megoldottuk

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/11
Írtam pár tesztet

**Comment by Szacsi5104** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/17
Benchmarkolás diagrammon ábrázolása és dokumentáció

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/15
Itt Laci írt unit testeket

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/16
Itt Szuki írt unit testeket

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/20
Itt Bence írt unit testeket

**Comment by darkpanther99** [comment]
Átnéztem a codecovot, és egy algo tesztje hiányzik, ennek utána kéne nézni/megcsinálni, utána zárható az Issue, a többi jó (Az rsa tesztje ki van kommentezve hosszú futás miatt, de ezt a dokumentációbvan említettük): https://codecov.io/gh/BME-MIT-IET/iet-hf2021-snek/src/84d5b423ee11b5cac3261f2514b5b7c0055f08e5/algorithms/dp/matrix_chain_order.py

**Comment by darkpanther99** [comment]
Szuki fixelte, itt a PR : https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/22
Ezután az Issuet zárom is, ezzel úgy látom, megvagyunk.
