### ISSUE TITLE
Nem-funkcionális jellemzők vizsgálata

### ISSUE THREAD

**Issue by darkpanther99** [BME-MIT-IET/iet-hf2021-snek#5]
Lehetne benchmarkokat, teljesítményteszteket futtatni az algoritmusainkhoz. Le kéne mérni, hogy tényleg fut-e olyan O értékkel, mint amit ígér az implementáció.

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/12
Itt megy a benchmarkolás

**Comment by Szacsi5104** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/17
Benchmarkolás diagrammon ábrázolása és dokumentáció
