### ISSUE TITLE
SonarCloud code smell fixek

### ISSUE THREAD

**Issue by szukiadam** [BME-MIT-IET/iet-hf2021-snek#6]
A sonarcloudban mutatott code smelleket kell fixelni.

**Comment by darkpanther99** [comment]
Átnéztem a code smelleket a SonarCloudon, és masterbe commitoltam változtatásokat, emellett írtam a lényegről dokumentációt. Azért a masterbe commitoltam, mert a Sonar új brancheken nem csinál teljes analízist, csak az újonnan írt kódot elemzi. Ezt "fix the leak mehod"-nak hívják, és ebben a fórum threadben lehet olvasni róla, hogy ez másoknak is probléma https://community.sonarsource.com/t/view-all-issues-in-a-branch-not-only-new-ones/12172/8

Voltak hibák, amiket átnéztem manuálisan a kódban, és arra jutottam, hogy false positive jelzések, ezért a Sonaron zártam be azokat. Ezek itt találhatók meg: https://sonarcloud.io/project/issues?id=BME-MIT-IET_iet-hf2021-snek&resolutions=FALSE-POSITIVE
