### ISSUE TITLE
SonarCloud bug fix 

### ISSUE THREAD

**Issue by szukiadam** [BME-MIT-IET/iet-hf2021-snek#8]
SonarCloudban mutatott bugokat kell kijavítani.

**Comment by darkpanther99** [comment]
https://github.com/BME-MIT-IET/iet-hf2021-snek/pull/9
Itt elvileg fixeltem a bugokat, mergelhetnénk masterbe.

**Comment by kovbe11** [comment]
A SonarCloud megfelelően működik zárom az issuet.
